# Generated by Django 3.2.12 on 2022-02-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
        ('payment', '0002_payment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_detail',
            name='clothes_num',
            field=models.ForeignKey(db_column='clothes_num', on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
        migrations.AlterField(
            model_name='payment_detail',
            name='payment_num',
            field=models.ForeignKey(db_column='payment_num', on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
    ]
