# Generated by Django 3.2.12 on 2022-02-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qna_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='redanse/QNA/%Y/%m/%d/%H/%M/%S')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-qna_num'],
            },
        ),
    ]
