# Generated by Django 3.2.9 on 2022-02-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_qna_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='qna_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
