# Generated by Django 3.2.12 on 2022-02-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.CharField(blank=True, choices=[('TOP', 'TOP'), ('BLOUSE & SHIRT', 'BLOUSE & SHIRT'), ('DRESS', 'DRESS'), ('PANTS', 'PANTS'), ('SKIRT', 'SKIRT'), ('OUTER', 'OUTER'), ('ACC & CAP', 'ACC & CAP')], max_length=18),
        ),
    ]
