# Generated by Django 3.2.12 on 2022-02-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.IntegerField(choices=[(0, 'TOP'), (1, 'BLOUSE & SHIRT'), (2, 'DRESS'), (3, 'PANTS'), (4, 'SKIRT'), (5, 'OUTER'), (6, 'ACC & CAP')]),
        ),
    ]
