# Generated by Django 3.2.12 on 2022-02-09 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('img1', models.ImageField(blank=True, upload_to='redanse/review/%Y/%m/%d/%H/%M/%S')),
                ('img2', models.ImageField(blank=True, upload_to='redanse/review/%Y/%m/%d/%H/%M/%S')),
                ('img3', models.ImageField(blank=True, upload_to='redanse/review/%Y/%m/%d/%H/%M/%S')),
                ('img4', models.ImageField(blank=True, upload_to='redanse/review/%Y/%m/%d/%H/%M/%S')),
                ('img5', models.ImageField(blank=True, upload_to='redanse/review/%Y/%m/%d/%H/%M/%S')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_detail_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment_detail')),
            ],
            options={
                'ordering': ['-payment_detail_num'],
            },
        ),
    ]
