# Generated by Django 3.2.12 on 2022-02-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_user_id'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='payment_detail_num',
            field=models.ForeignKey(db_column='payment_detail_num', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payment.payment_detail'),
        ),
    ]
