# Generated by Django 3.2.9 on 2022-02-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20220216_1523'),
        ('review', '0004_alter_review_payment_detail_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='payment_detail_num',
            field=models.ForeignKey(db_column='payment_detail_num', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='review', serialize=False, to='payment.payment_detail'),
        ),
    ]
