# Generated by Django 3.2.12 on 2022-02-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_num', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('clothes_num', models.ForeignKey(db_column='clothes_num', on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
            options={
                'ordering': ['-cart_num'],
            },
        ),
    ]
