# Generated by Django 3.2.9 on 2022-02-18 03:16

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rental_date',
            field=models.DateField(default=cart.models.default_date),
        ),
        migrations.AddField(
            model_name='cart',
            name='return_date',
            field=models.DateField(default=cart.models.default_returndate),
        ),
    ]
