# Generated by Django 3.2.12 on 2022-02-07 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')])),
                ('user_pw', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='특수문자(!@#$%^&*)를 포함한 최소 8글자 이상의 문자를 입력해주세요.', regex='^[a-zA-Z0-9!@#$%^&*]*$')])),
                ('user_nickname', models.CharField(max_length=18, unique=True)),
                ('user_tel', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3,4}-\\d{4}$')])),
                ('user_birth', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}-\\d{2}$')])),
                ('user_genre', models.CharField(choices=[('팝핀', '팝핀'), ('브레이킹', '브레이킹'), ('락킹', '락킹'), ('왁킹', '왁킹'), ('힙합', '힙합'), ('하우스', '하우스'), ('크럼프', '크럼프'), ('기타', '기타')], max_length=18)),
                ('user_type', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('user_auth', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('user_signupdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-user_signupdate'],
            },
        ),
    ]
